name: Train Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-learn joblib

    - name: Train model
      run: python train_model.py

    - name: Upload trained model
      uses: actions/upload-artifact@v3
      with:
        name: iris-model
        path: iris_model.pkl
